/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Placar;
import javax.swing.JOptionPane;

/**
 *
 * @author ramom
 */
public class PlacarJogo extends javax.swing.JFrame {

    Placar placar;

    /**
     * Creates new form Placar
     */
    public PlacarJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAddEquipe2 = new javax.swing.JButton();
        btRemEquipe2 = new javax.swing.JButton();
        btAddEquipe1 = new javax.swing.JButton();
        btRemEquipe1 = new javax.swing.JButton();
        tfNomeEquipe2 = new javax.swing.JTextField();
        tfNomeEquipe1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfSetsEquipe2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSetsEquipe1 = new javax.swing.JTextField();
        tfPontosEquipe1 = new javax.swing.JTextField();
        tfPontosEquipe2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfHorario = new javax.swing.JTextField();
        btIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAddEquipe2.setText("+");
        btAddEquipe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddEquipe2ActionPerformed(evt);
            }
        });

        btRemEquipe2.setText("-");
        btRemEquipe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemEquipe2ActionPerformed(evt);
            }
        });

        btAddEquipe1.setText("+");
        btAddEquipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddEquipe1ActionPerformed(evt);
            }
        });

        btRemEquipe1.setText("-");
        btRemEquipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemEquipe1ActionPerformed(evt);
            }
        });

        tfNomeEquipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeEquipe1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome da Equipe 1");

        jLabel2.setText("Nome da Equipe 2");

        jLabel3.setText("Sets");

        tfSetsEquipe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSetsEquipe2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Sets");

        tfPontosEquipe1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        tfPontosEquipe2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jLabel5.setText("Horário");

        btIniciar.setText("Iniciar Jogo");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        taMostrar.setEditable(false);
        taMostrar.setColumns(20);
        taMostrar.setRows(5);
        taMostrar.setAutoscrolls(false);
        jScrollPane1.setViewportView(taMostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btAddEquipe1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btRemEquipe1))
                                    .addComponent(tfNomeEquipe1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfSetsEquipe1)))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel5)
                                        .addGap(8, 8, 8))
                                    .addComponent(tfHorario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 81, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tfPontosEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfSetsEquipe2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAddEquipe2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRemEquipe2))
                            .addComponent(tfNomeEquipe2)
                            .addComponent(tfPontosEquipe2))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btIniciar)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSetsEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfSetsEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPontosEquipe1)
                    .addComponent(tfPontosEquipe2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddEquipe2)
                    .addComponent(btRemEquipe2)
                    .addComponent(btAddEquipe1)
                    .addComponent(btRemEquipe1))
                .addGap(32, 32, 32)
                .addComponent(btIniciar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        if (!tfNomeEquipe1.getText().equals("") || !tfNomeEquipe2.getText().equals("") || !tfHorario.getText().equals("")) {
            placar = new Placar(tfNomeEquipe1.getText(), tfNomeEquipe2.getText(), tfHorario.getText());

            tfPontosEquipe1.setText(Integer.toString(placar.getPontosEquipe1()));
            tfPontosEquipe2.setText(Integer.toString(placar.getPontosEquipe2()));
            tfSetsEquipe1.setText(Integer.toString(placar.getSetsEquipe1()));
            tfSetsEquipe2.setText(Integer.toString(placar.getSetsEquipe2()));
            btIniciar.disable();
            JOptionPane.showMessageDialog(null, "O jogo foi iniciado!");
        } else {
            JOptionPane.showMessageDialog(null, "Você precisa colocar os nomes e o horário para iniciar o jogo");
        }
    }//GEN-LAST:event_btIniciarActionPerformed

    private void tfNomeEquipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeEquipe1ActionPerformed

    }//GEN-LAST:event_tfNomeEquipe1ActionPerformed

    private void tfSetsEquipe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSetsEquipe2ActionPerformed

    }//GEN-LAST:event_tfSetsEquipe2ActionPerformed

    private void btAddEquipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddEquipe1ActionPerformed
        placar.addEquipe1();
        tfPontosEquipe1.setText(Integer.toString(placar.getPontosEquipe1()));
        int Vencedor = placar.VerificaVencedorSet(placar.getPontosEquipe1(), placar.getPontosEquipe2(), placar.getSetAtual());

        verificaVencedor(Vencedor);
       

    }//GEN-LAST:event_btAddEquipe1ActionPerformed

    private void btAddEquipe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddEquipe2ActionPerformed
        placar.addEquipe2();
        tfPontosEquipe2.setText(Integer.toString(placar.getPontosEquipe2()));
        int Vencedor = placar.VerificaVencedorSet(placar.getPontosEquipe1(), placar.getPontosEquipe2(), placar.getSetAtual());

        verificaVencedor(Vencedor);


    }//GEN-LAST:event_btAddEquipe2ActionPerformed

    private void btRemEquipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemEquipe1ActionPerformed
        placar.RemoveEquipe1();
        tfPontosEquipe1.setText(Integer.toString(placar.getPontosEquipe1()));
    }//GEN-LAST:event_btRemEquipe1ActionPerformed

    private void btRemEquipe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemEquipe2ActionPerformed
        placar.RemoveEquipe2();
        tfPontosEquipe2.setText(Integer.toString(placar.getPontosEquipe2()));
    }//GEN-LAST:event_btRemEquipe2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacarJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddEquipe1;
    private javax.swing.JButton btAddEquipe2;
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btRemEquipe1;
    private javax.swing.JButton btRemEquipe2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taMostrar;
    private javax.swing.JTextField tfHorario;
    private javax.swing.JTextField tfNomeEquipe1;
    private javax.swing.JTextField tfNomeEquipe2;
    private javax.swing.JTextField tfPontosEquipe1;
    private javax.swing.JTextField tfPontosEquipe2;
    private javax.swing.JTextField tfSetsEquipe1;
    private javax.swing.JTextField tfSetsEquipe2;
    // End of variables declaration//GEN-END:variables

    
    public void verificaVencedorJogo(int pontosSet1, int pontosSet2){
        int vencedor = placar.VerificaVencedor(pontosSet1, pontosSet2);
        if(vencedor == 1){
            JOptionPane.showMessageDialog(null, "A equipe 1 venceu o jogo");
        }else if(vencedor == 2){
              JOptionPane.showMessageDialog(null, "A equipe 2 venceu o jogo");
        }
    }
    public void verificaVencedor(int Vencedor) {
        if (Vencedor == 1) {
            JOptionPane.showMessageDialog(null, "O vencedor do set foi a equipe 1");
            placar.addSetAtual();
            placar.addSetEquipe1();
            tfSetsEquipe1.setText(Integer.toString(placar.getSetsEquipe1()));
            taMostrar.append(placar.getPontosEquipe1() + " - " + placar.getPontosEquipe2() + "\n");
            placar.ZerarPlacar();
            tfPontosEquipe2.setText(Integer.toString(placar.getPontosEquipe2()));
            tfPontosEquipe1.setText(Integer.toString(placar.getPontosEquipe1()));
            verificaVencedorJogo(placar.getSetsEquipe1(), placar.getSetsEquipe2());
            
        } else if (Vencedor == 2) {
            JOptionPane.showMessageDialog(null, "O vencedor do set foi a equipe 2");
            placar.addSetAtual();
            placar.addSetEquipe2();
            tfSetsEquipe2.setText(Integer.toString(placar.getSetsEquipe2()));
            taMostrar.append(placar.getPontosEquipe1() + " - " + placar.getPontosEquipe2() + "\n");
            placar.ZerarPlacar();
            tfPontosEquipe2.setText(Integer.toString(placar.getPontosEquipe2()));
            tfPontosEquipe1.setText(Integer.toString(placar.getPontosEquipe1()));
            verificaVencedorJogo(placar.getSetsEquipe1(), placar.getSetsEquipe2());
            
        }
    }
}
